services:
  - type: web
    name: rowpress
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    autoDeployTrigger: checksPass
    # maxShutdownDelaySeconds: 15 # Not supported on free plan
    envVars:
      - key: BASIC_AUTH_USERNAME
        sync: false
      - key: BASIC_AUTH_PASSWORD
        sync: false
